/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int NEWVAR = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int PVIRGULA = 11;
  /** RegularExpression Id. */
  int BOOL = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int THEN = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int REPEAT = 16;
  /** RegularExpression Id. */
  int UNTIL = 17;
  /** RegularExpression Id. */
  int RETURN = 18;
  /** RegularExpression Id. */
  int PRINT = 19;
  /** RegularExpression Id. */
  int APAREN = 20;
  /** RegularExpression Id. */
  int FPAREN = 21;
  /** RegularExpression Id. */
  int IGUAL = 22;
  /** RegularExpression Id. */
  int VIRGULA = 23;
  /** RegularExpression Id. */
  int NFUNC = 24;
  /** RegularExpression Id. */
  int OP = 25;
  /** RegularExpression Id. */
  int ID = 26;
  /** RegularExpression Id. */
  int NUMLITERAL = 27;
  /** RegularExpression Id. */
  int BOOLEANO = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"void\"",
    "\"newVar\"",
    "\"int\"",
    "\";\"",
    "\"bool\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"repeat\"",
    "\"until\"",
    "\"return\"",
    "\"System.output\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\",\"",
    "\"func\"",
    "<OP>",
    "<ID>",
    "<NUMLITERAL>",
    "<BOOLEANO>",
  };

}
